-- Settings for monetization limits
INSERT INTO site_settings (key, value) VALUES
('layanan_free_limit_days', '3'),
('ai_free_daily_limit', '3'),
('quran_free_daily_limit', '5'),
('fast_track_price', '50'),
('theme_premium_price', '100'),
('badge_vip_price', '500'),
('tafsir_ai_price', '10')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Table for premium documents
CREATE TABLE IF NOT EXISTS premium_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT NOT NULL,
  is_early_access BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for user themes and badges (if not exists)
CREATE TABLE IF NOT EXISTS user_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL, -- 'theme', 'badge'
  item_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, item_type, item_id)
);

-- Modify increment_feature_usage to support window tracking (e.g. 3 days)
CREATE OR REPLACE FUNCTION check_and_increment_usage(p_user_id UUID, p_feature_name VARCHAR, p_limit INTEGER, p_window_days INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
    v_usage_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_usage_count
    FROM user_feature_usage
    WHERE user_id = p_user_id
      AND feature_name = p_feature_name
      AND usage_date >= (CURRENT_DATE - (p_window_days || ' days')::interval);

    IF v_usage_count >= p_limit THEN
        RETURN FALSE;
    END IF;

    INSERT INTO user_feature_usage (user_id, feature_name, usage_date, usage_count, last_used_at)
    VALUES (p_user_id, p_feature_name, CURRENT_DATE, 1, NOW())
    ON CONFLICT (user_id, feature_name, usage_date)
    DO UPDATE SET
        usage_count = user_feature_usage.usage_count + 1,
        last_used_at = NOW();

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
