import {
  FaCalculator, FaExchangeAlt, FaFont, FaClock, FaFileAlt,
  FaImage, FaGlobe, FaCode, FaSquareRootAlt, FaBriefcase,
  FaSearch, FaLock, FaRandom
} from 'react-icons/fa';

export const categories = [
  { id: 'all', name: 'Semua Tools', icon: FaSearch },
  { id: 'calculator', name: 'Kalkulator', icon: FaCalculator },
  { id: 'converter', name: 'Converter', icon: FaExchangeAlt },
  { id: 'text', name: 'Teks', icon: FaFont },
  { id: 'datetime', name: 'Tanggal & Waktu', icon: FaClock },
  { id: 'file', name: 'File', icon: FaFileAlt },
  { id: 'image', name: 'Gambar & Warna', icon: FaImage },
  { id: 'web', name: 'Internet & Web', icon: FaGlobe },
  { id: 'developer', name: 'Developer', icon: FaCode },
  { id: 'math', name: 'Matematika', icon: FaSquareRootAlt },
  { id: 'business', name: 'Bisnis & Produktivitas', icon: FaBriefcase },
  { id: 'seo', name: 'SEO & Konten', icon: FaSearch },
  { id: 'security', name: 'Keamanan', icon: FaLock },
  { id: 'random', name: 'Random Generator', icon: FaRandom },
];

export const toolsData = [
  // Kalkulator
  { id: 'calc-basic', name: 'Kalkulator Biasa', desc: 'Kalkulator standar untuk operasi dasar', category: 'calculator', type: 'GenericCalculatorTool', config: 'basic' },
  { id: 'calc-scientific', name: 'Kalkulator Ilmiah', desc: 'Kalkulator dengan fungsi matematika lanjutan', category: 'calculator', type: 'GenericCalculatorTool', config: 'scientific' },
  { id: 'calc-percent', name: 'Kalkulator Persen', desc: 'Hitung persentase dengan mudah', category: 'calculator', type: 'GenericCalculatorTool', config: 'percent' },
  { id: 'calc-discount', name: 'Kalkulator Diskon', desc: 'Hitung harga setelah diskon', category: 'calculator', type: 'GenericCalculatorTool', config: 'discount' },
  { id: 'calc-tax', name: 'Kalkulator Pajak', desc: 'Hitung pajak (PPN, dll)', category: 'calculator', type: 'GenericCalculatorTool', config: 'tax' },
  { id: 'calc-interest', name: 'Kalkulator Bunga', desc: 'Hitung bunga tunggal/majemuk', category: 'calculator', type: 'GenericCalculatorTool', config: 'interest' },
  { id: 'calc-installment', name: 'Kalkulator Cicilan', desc: 'Hitung cicilan pinjaman per bulan', category: 'calculator', type: 'GenericCalculatorTool', config: 'installment' },
  { id: 'calc-bmi', name: 'Kalkulator BMI', desc: 'Hitung Indeks Massa Tubuh', category: 'calculator', type: 'GenericCalculatorTool', config: 'bmi' },
  { id: 'calc-calorie', name: 'Kalkulator Kalori', desc: 'Hitung kebutuhan kalori harian', category: 'calculator', type: 'GenericCalculatorTool', config: 'calorie' },
  { id: 'calc-age', name: 'Kalkulator Usia', desc: 'Hitung usia akurat berdasarkan tanggal lahir', category: 'calculator', type: 'GenericCalculatorTool', config: 'age' },
  { id: 'calc-travel-time', name: 'Kalkulator Waktu Tempuh', desc: 'Hitung estimasi waktu tempuh perjalanan', category: 'calculator', type: 'GenericCalculatorTool', config: 'travelTime' },
  { id: 'calc-area-volume', name: 'Kalkulator Luas & Volume', desc: 'Hitung luas dan volume berbagai bangun', category: 'calculator', type: 'GenericCalculatorTool', config: 'areaVolume' },
  { id: 'calc-speed', name: 'Kalkulator Kecepatan', desc: 'Hitung kecepatan, jarak, atau waktu', category: 'calculator', type: 'GenericCalculatorTool', config: 'speed' },
  { id: 'calc-fraction', name: 'Kalkulator Pecahan', desc: 'Operasi matematika dengan pecahan', category: 'calculator', type: 'GenericCalculatorTool', config: 'fraction' },
  { id: 'calc-root-log', name: 'Akar, Pangkat, Logaritma', desc: 'Hitung akar, pangkat, dan logaritma', category: 'calculator', type: 'GenericCalculatorTool', config: 'rootLog' },

  // Converter
  { id: 'conv-length', name: 'Konversi Panjang', desc: 'cm, m, km, inch, feet, mile', category: 'converter', type: 'GenericConverterTool', config: 'length' },
  { id: 'conv-weight', name: 'Konversi Berat', desc: 'gram, kg, ton, pound', category: 'converter', type: 'GenericConverterTool', config: 'weight' },
  { id: 'conv-temp', name: 'Konversi Suhu', desc: 'Celsius, Fahrenheit, Kelvin', category: 'converter', type: 'GenericConverterTool', config: 'temp' },
  { id: 'conv-currency', name: 'Konversi Mata Uang', desc: 'Konversi nilai tukar mata uang', category: 'converter', type: 'GenericConverterTool', config: 'currency' },
  { id: 'conv-time', name: 'Konversi Waktu', desc: 'detik, menit, jam, hari', category: 'converter', type: 'GenericConverterTool', config: 'time' },
  { id: 'conv-volume', name: 'Konversi Volume', desc: 'liter, ml, galon', category: 'converter', type: 'GenericConverterTool', config: 'volume' },
  { id: 'conv-area', name: 'Konversi Luas', desc: 'hektar, meter persegi, acre', category: 'converter', type: 'GenericConverterTool', config: 'area' },
  { id: 'conv-speed', name: 'Konversi Kecepatan', desc: 'km/h, mph, m/s, knot', category: 'converter', type: 'GenericConverterTool', config: 'speed' },
  { id: 'conv-data', name: 'Konversi Ukuran Data', desc: 'KB, MB, GB, TB', category: 'converter', type: 'GenericConverterTool', config: 'data' },
  { id: 'conv-roman', name: 'Konversi Angka Romawi', desc: 'Desimal ke Romawi dan sebaliknya', category: 'converter', type: 'GenericConverterTool', config: 'roman' },
  { id: 'conv-base', name: 'Konversi Basis Angka', desc: 'Biner, desimal, heksadesimal', category: 'converter', type: 'GenericConverterTool', config: 'base' },
  { id: 'conv-color', name: 'Konversi Warna', desc: 'HEX, RGB, HSL', category: 'converter', type: 'GenericConverterTool', config: 'color' },

  // Text
  { id: 'txt-count', name: 'Penghitung Kata & Karakter', desc: 'Hitung jumlah kata, karakter, dan kalimat', category: 'text', type: 'GenericTextTool', config: 'count' },
  { id: 'txt-case', name: 'Pengubah Huruf', desc: 'Besar/kecil, kapitalisasi tiap kata', category: 'text', type: 'GenericTextTool', config: 'case' },
  { id: 'txt-slug', name: 'Text to Slug', desc: 'Ubah teks menjadi URL slug', category: 'text', type: 'GenericTextTool', config: 'slug' },
  { id: 'txt-space', name: 'Hapus Spasi Berlebih', desc: 'Bersihkan spasi ganda dalam teks', category: 'text', type: 'GenericTextTool', config: 'space' },
  { id: 'txt-empty-line', name: 'Hapus Baris Kosong', desc: 'Hapus baris kosong (enter) berlebih', category: 'text', type: 'GenericTextTool', config: 'emptyLine' },
  { id: 'txt-sort', name: 'Sortir Teks A-Z', desc: 'Urutkan daftar teks secara alfabetis', category: 'text', type: 'GenericTextTool', config: 'sort' },
  { id: 'txt-random', name: 'Random Text Generator', desc: 'Hasilkan teks acak', category: 'text', type: 'GenericTextTool', config: 'random' },
  { id: 'txt-lorem', name: 'Lorem Ipsum Generator', desc: 'Buat teks dummy lorem ipsum', category: 'text', type: 'GenericTextTool', config: 'lorem' },
  { id: 'txt-reverse', name: 'Reverse Text', desc: 'Balikkan urutan karakter teks', category: 'text', type: 'GenericTextTool', config: 'reverse' },
  { id: 'txt-replace', name: 'Find and Replace', desc: 'Cari dan ganti kata dalam teks', category: 'text', type: 'GenericTextTool', config: 'replace' },
  { id: 'txt-format', name: 'Text Formatter', desc: 'Format teks berantakan menjadi rapi', category: 'text', type: 'GenericTextTool', config: 'format' },
  { id: 'txt-markdown', name: 'Markdown Preview', desc: 'Tulis dan preview kode Markdown', category: 'text', type: 'GenericTextTool', config: 'markdown' },

  // Date & Time
  { id: 'dt-world', name: 'Jam Dunia', desc: 'Cek waktu di berbagai zona waktu', category: 'datetime', type: 'SpecificTools', config: 'worldClock' },
  { id: 'dt-stopwatch', name: 'Stopwatch', desc: 'Stopwatch dengan fitur lap', category: 'datetime', type: 'SpecificTools', config: 'stopwatch' },
  { id: 'dt-timer', name: 'Timer / Countdown', desc: 'Penghitung waktu mundur', category: 'datetime', type: 'SpecificTools', config: 'timer' },
  { id: 'dt-calendar', name: 'Kalender', desc: 'Kalender interaktif', category: 'datetime', type: 'SpecificTools', config: 'calendar' },
  { id: 'dt-diff', name: 'Hitung Selisih Tanggal', desc: 'Hitung jarak antar dua tanggal', category: 'datetime', type: 'SpecificTools', config: 'dateDiff' },
  { id: 'dt-add-sub', name: 'Tambah/Kurangi Hari', desc: 'Kalkulasi tanggal dari hari ini', category: 'datetime', type: 'SpecificTools', config: 'addSubtract' },
  { id: 'dt-timezone', name: 'Konversi Zona Waktu', desc: 'Ubah waktu antar zona', category: 'datetime', type: 'SpecificTools', config: 'timezone' },
  { id: 'dt-timestamp', name: 'Timestamp Converter', desc: 'Unix time ke format tanggal', category: 'datetime', type: 'SpecificTools', config: 'timestamp' },
  { id: 'dt-day-of-year', name: 'Hari Keberapa', desc: 'Cek ini hari keberapa dalam setahun', category: 'datetime', type: 'SpecificTools', config: 'dayOfYear' },
  { id: 'dt-schedule', name: 'Generator Jadwal', desc: 'Buat jadwal sederhana', category: 'datetime', type: 'SpecificTools', config: 'schedule' },

  // File
  { id: 'file-pdf-word', name: 'PDF to Word', desc: 'Ubah file PDF menjadi Word (Simulasi)', category: 'file', type: 'SpecificTools', config: 'pdfWord' },
  { id: 'file-word-pdf', name: 'Word to PDF', desc: 'Ubah file Word menjadi PDF (Simulasi)', category: 'file', type: 'SpecificTools', config: 'wordPdf' },
  { id: 'file-jpg-pdf', name: 'JPG to PDF', desc: 'Ubah gambar JPG menjadi PDF', category: 'file', type: 'SpecificTools', config: 'jpgPdf' },
  { id: 'file-png-jpg', name: 'PNG to JPG', desc: 'Ubah gambar PNG menjadi JPG', category: 'file', type: 'SpecificTools', config: 'pngJpg' },
  { id: 'file-compress-pdf', name: 'Compress PDF', desc: 'Kurangi ukuran file PDF (Simulasi)', category: 'file', type: 'SpecificTools', config: 'compressPdf' },
  { id: 'file-merge-pdf', name: 'Merge PDF', desc: 'Gabungkan beberapa file PDF (Simulasi)', category: 'file', type: 'SpecificTools', config: 'mergePdf' },
  { id: 'file-split-pdf', name: 'Split PDF', desc: 'Pisahkan halaman file PDF (Simulasi)', category: 'file', type: 'SpecificTools', config: 'splitPdf' },
  { id: 'file-resize-img', name: 'Resize Image', desc: 'Ubah dimensi gambar', category: 'file', type: 'SpecificTools', config: 'resizeImg' },
  { id: 'file-compress-img', name: 'Compress Image', desc: 'Kurangi ukuran file gambar', category: 'file', type: 'SpecificTools', config: 'compressImg' },
  { id: 'file-rename', name: 'Rename File Generator', desc: 'Buat format nama file masal', category: 'file', type: 'SpecificTools', config: 'rename' },
  { id: 'file-size', name: 'File Size Checker', desc: 'Cek rincian ukuran file', category: 'file', type: 'SpecificTools', config: 'fileSize' },
  { id: 'file-qr', name: 'QR Code dari File', desc: 'Buat QR untuk link file', category: 'file', type: 'SpecificTools', config: 'fileQr' },
  { id: 'file-base64', name: 'Base64 File Encode', desc: 'Ubah file menjadi string Base64', category: 'file', type: 'SpecificTools', config: 'fileBase64' },

  // Image & Color
  { id: 'img-color-picker', name: 'Color Picker', desc: 'Ambil kode warna', category: 'image', type: 'SpecificTools', config: 'colorPicker' },
  { id: 'img-palette', name: 'Palette Generator', desc: 'Hasilkan palet warna menarik', category: 'image', type: 'SpecificTools', config: 'palette' },
  { id: 'img-gradient', name: 'Gradient Generator', desc: 'Buat CSS gradient', category: 'image', type: 'SpecificTools', config: 'gradient' },
  { id: 'img-crop', name: 'Image Cropper', desc: 'Potong gambar sesuai rasio', category: 'image', type: 'SpecificTools', config: 'cropper' },
  { id: 'img-bg-remove', name: 'Background Remover', desc: 'Hapus latar belakang (Simulasi)', category: 'image', type: 'SpecificTools', config: 'bgRemove' },
  { id: 'img-favicon', name: 'Favicon Generator', desc: 'Buat favicon untuk web', category: 'image', type: 'SpecificTools', config: 'favicon' },
  { id: 'img-logo-size', name: 'Logo Size Checker', desc: 'Cek kesesuaian ukuran logo', category: 'image', type: 'SpecificTools', config: 'logoSize' },
  { id: 'img-aspect', name: 'Aspect Ratio Calc', desc: 'Kalkulator rasio gambar', category: 'image', type: 'SpecificTools', config: 'aspectRatio' },
  { id: 'img-hex-rgb', name: 'HEX to RGB Converter', desc: 'Konversi kode warna', category: 'image', type: 'SpecificTools', config: 'hexRgb' },
  { id: 'img-contrast', name: 'Contrast Checker', desc: 'Cek kontras warna untuk aksesibilitas', category: 'image', type: 'SpecificTools', config: 'contrast' },

  // Web
  { id: 'web-qr', name: 'QR Code Generator', desc: 'Buat kode QR kustom', category: 'web', type: 'SpecificTools', config: 'qrGenerator' },
  { id: 'web-shorturl', name: 'URL Shortener', desc: 'Persingkat link URL panjang', category: 'web', type: 'SpecificTools', config: 'urlShortener' },
  { id: 'web-url-encode', name: 'URL Encoder/Decoder', desc: 'Encode URL karakter khusus', category: 'web', type: 'SpecificTools', config: 'urlEncode' },
  { id: 'web-utm', name: 'UTM Builder', desc: 'Buat link tracking UTM', category: 'web', type: 'SpecificTools', config: 'utm' },
  { id: 'web-meta', name: 'Meta Tag Generator', desc: 'Buat meta tag HTML SEO', category: 'web', type: 'SpecificTools', config: 'metaTag' },
  { id: 'web-og', name: 'Open Graph Preview', desc: 'Preview tampilan share sosial media', category: 'web', type: 'SpecificTools', config: 'ogPreview' },
  { id: 'web-robots', name: 'Robots.txt Generator', desc: 'Buat file robots.txt', category: 'web', type: 'SpecificTools', config: 'robotsTxt' },
  { id: 'web-sitemap', name: 'Sitemap Generator', desc: 'Buat sitemap XML dasar', category: 'web', type: 'SpecificTools', config: 'sitemap' },
  { id: 'web-http', name: 'HTTP Status Checker', desc: 'Cek status kode respon URL', category: 'web', type: 'SpecificTools', config: 'httpStatus' },
  { id: 'web-redirect', name: 'Redirect Checker', desc: 'Cek jalur redirect URL', category: 'web', type: 'SpecificTools', config: 'redirect' },
  { id: 'web-dns', name: 'DNS Lookup', desc: 'Cek record DNS domain', category: 'web', type: 'SpecificTools', config: 'dns' },
  { id: 'web-whois', name: 'Whois Lookup', desc: 'Cek informasi kepemilikan domain', category: 'web', type: 'SpecificTools', config: 'whois' },
  { id: 'web-ping', name: 'Ping Website', desc: 'Cek latensi server web', category: 'web', type: 'SpecificTools', config: 'ping' },
  { id: 'web-speed', name: 'Website Speed Checker', desc: 'Cek kecepatan akses', category: 'web', type: 'SpecificTools', config: 'speedTest' },
  { id: 'web-ssl', name: 'SSL Checker', desc: 'Cek validitas sertifikat SSL', category: 'web', type: 'SpecificTools', config: 'ssl' },

  // Developer
  { id: 'dev-json-fmt', name: 'JSON Formatter', desc: 'Format & percantik data JSON', category: 'developer', type: 'SpecificTools', config: 'jsonFmt' },
  { id: 'dev-json-val', name: 'JSON Validator', desc: 'Validasi struktur data JSON', category: 'developer', type: 'SpecificTools', config: 'jsonVal' },
  { id: 'dev-xml-fmt', name: 'XML Formatter', desc: 'Format data XML', category: 'developer', type: 'SpecificTools', config: 'xmlFmt' },
  { id: 'dev-html-fmt', name: 'HTML Formatter', desc: 'Format kode HTML', category: 'developer', type: 'SpecificTools', config: 'htmlFmt' },
  { id: 'dev-css-fmt', name: 'CSS Formatter', desc: 'Format kode CSS', category: 'developer', type: 'SpecificTools', config: 'cssFmt' },
  { id: 'dev-js-fmt', name: 'JavaScript Formatter', desc: 'Format kode JS', category: 'developer', type: 'SpecificTools', config: 'jsFmt' },
  { id: 'dev-minify', name: 'Minify HTML/CSS/JS', desc: 'Kompres ukuran source code', category: 'developer', type: 'SpecificTools', config: 'minify' },
  { id: 'dev-regex', name: 'Regex Tester', desc: 'Uji Regular Expression', category: 'developer', type: 'SpecificTools', config: 'regex' },
  { id: 'dev-jwt', name: 'JWT Decoder', desc: 'Decode token JSON Web Token', category: 'developer', type: 'SpecificTools', config: 'jwt' },
  { id: 'dev-base64', name: 'Base64 Encode/Decode', desc: 'Ubah teks ke Base64', category: 'developer', type: 'SpecificTools', config: 'base64' },
  { id: 'dev-uuid', name: 'UUID Generator', desc: 'Buat Unique ID', category: 'developer', type: 'SpecificTools', config: 'uuid' },
  { id: 'dev-hash', name: 'Hash Generator', desc: 'MD5, SHA-1, SHA-256', category: 'developer', type: 'SpecificTools', config: 'hash' },
  { id: 'dev-lorem-api', name: 'Lorem API Tester', desc: 'Test endpoint API dummy', category: 'developer', type: 'SpecificTools', config: 'loremApi' },
  { id: 'dev-cron', name: 'Cron Expression', desc: 'Generator kode Cron schedule', category: 'developer', type: 'SpecificTools', config: 'cron' },

  // Math & Education
  { id: 'math-graph', name: 'Pembuat Grafik', desc: 'Plot grafik fungsi matematika', category: 'math', type: 'SpecificTools', config: 'graph' },
  { id: 'math-solver', name: 'Solver Persamaan', desc: 'Pecahkan persamaan linier/kuadrat', category: 'math', type: 'SpecificTools', config: 'solver' },
  { id: 'math-average', name: 'Kalkulator Rata-rata', desc: 'Hitung mean dari deret angka', category: 'math', type: 'SpecificTools', config: 'average' },
  { id: 'math-median', name: 'Median dan Modus', desc: 'Cari nilai tengah dan terbanyak', category: 'math', type: 'SpecificTools', config: 'median' },
  { id: 'math-prob', name: 'Kalkulator Probabilitas', desc: 'Hitung peluang kejadian', category: 'math', type: 'SpecificTools', config: 'probability' },
  { id: 'math-geometry', name: 'Kalkulator Geometri', desc: 'Hitung sisi miring, luas alas', category: 'math', type: 'SpecificTools', config: 'geometry' },
  { id: 'math-trigo', name: 'Trigonometri', desc: 'Sin, Cos, Tan', category: 'math', type: 'SpecificTools', config: 'trigo' },
  { id: 'math-physics', name: 'Konversi Satuan Fisika', desc: 'Gaya, energi, tekanan', category: 'math', type: 'SpecificTools', config: 'physics' },
  { id: 'math-periodic', name: 'Tabel Periodik', desc: 'Informasi unsur kimia', category: 'math', type: 'SpecificTools', config: 'periodic' },
  { id: 'math-formulas', name: 'Rumus Matematika', desc: 'Kumpulan rumus penting', category: 'math', type: 'SpecificTools', config: 'formulas' },
  { id: 'math-exercise', name: 'Generator Soal', desc: 'Buat soal latihan acak', category: 'math', type: 'SpecificTools', config: 'exercise' },
  { id: 'math-flashcard', name: 'Flashcard Sederhana', desc: 'Alat bantu hafal materi', category: 'math', type: 'SpecificTools', config: 'flashcard' },

  // Business
  { id: 'biz-invoice', name: 'Invoice Generator', desc: 'Buat tagihan pro forma', category: 'business', type: 'SpecificTools', config: 'invoice' },
  { id: 'biz-receipt', name: 'Receipt Generator', desc: 'Buat struk bukti bayar', category: 'business', type: 'SpecificTools', config: 'receipt' },
  { id: 'biz-todo', name: 'To-do List', desc: 'Catat daftar tugas harian', category: 'business', type: 'SpecificTools', config: 'todo' },
  { id: 'biz-notes', name: 'Notes Online', desc: 'Catatan ringan', category: 'business', type: 'SpecificTools', config: 'notes' },
  { id: 'biz-pomodoro', name: 'Pomodoro Timer', desc: 'Teknik manajemen waktu 25 menit', category: 'business', type: 'SpecificTools', config: 'pomodoro' },
  { id: 'biz-salary', name: 'Kalkulator Gaji', desc: 'Hitung THP dan potongan', category: 'business', type: 'GenericCalculatorTool', config: 'salary' },
  { id: 'biz-margin', name: 'Kalkulator Profit Margin', desc: 'Hitung persentase keuntungan', category: 'business', type: 'GenericCalculatorTool', config: 'margin' },
  { id: 'biz-markup', name: 'Kalkulator Markup', desc: 'Tentukan harga jual', category: 'business', type: 'GenericCalculatorTool', config: 'markup' },
  { id: 'biz-roi', name: 'Kalkulator ROI', desc: 'Return on Investment', category: 'business', type: 'GenericCalculatorTool', config: 'roi' },
  { id: 'biz-bep', name: 'Break Even Point', desc: 'Hitung titik impas', category: 'business', type: 'GenericCalculatorTool', config: 'bep' },
  { id: 'biz-name', name: 'Generator Nama Bisnis', desc: 'Ide nama usaha', category: 'business', type: 'GenericGeneratorTool', config: 'bizName' },
  { id: 'biz-content', name: 'Generator Ide Konten', desc: 'Ide postingan sosmed', category: 'business', type: 'GenericGeneratorTool', config: 'contentIdea' },
  { id: 'biz-email', name: 'Template Email', desc: 'Format email profesional', category: 'business', type: 'SpecificTools', config: 'emailTpl' },
  { id: 'biz-proposal', name: 'Template Proposal', desc: 'Draft proposal bisnis', category: 'business', type: 'SpecificTools', config: 'proposalTpl' },
  { id: 'biz-checklist', name: 'Checklist Generator', desc: 'Buat daftar periksa', category: 'business', type: 'SpecificTools', config: 'checklist' },

  // SEO
  { id: 'seo-keyword', name: 'Keyword Density', desc: 'Cek kepadatan kata kunci', category: 'seo', type: 'SpecificTools', config: 'keyword' },
  { id: 'seo-title', name: 'Meta Title Checker', desc: 'Cek panjang optimal judul SEO', category: 'seo', type: 'SpecificTools', config: 'metaTitle' },
  { id: 'seo-desc', name: 'Meta Desc Checker', desc: 'Cek panjang optimal deskripsi SEO', category: 'seo', type: 'SpecificTools', config: 'metaDesc' },
  { id: 'seo-slug', name: 'Slug Generator', desc: 'Buat URL ramah SEO', category: 'seo', type: 'GenericTextTool', config: 'slug' },
  { id: 'seo-heading', name: 'Heading Checker', desc: 'Analisa struktur tag H1-H6', category: 'seo', type: 'SpecificTools', config: 'heading' },
  { id: 'seo-readability', name: 'Readability Checker', desc: 'Cek skor kemudahan baca', category: 'seo', type: 'SpecificTools', config: 'readability' },
  { id: 'seo-plagiarism', name: 'Plagiarism Checker', desc: 'Cek kemiripan teks (Simulasi)', category: 'seo', type: 'SpecificTools', config: 'plagiarism' },
  { id: 'seo-outline', name: 'Artikel Outline', desc: 'Generator kerangka tulisan', category: 'seo', type: 'SpecificTools', config: 'outline' },
  { id: 'seo-hashtag', name: 'Hashtag Generator', desc: 'Buat tag populer', category: 'seo', type: 'SpecificTools', config: 'hashtag' },
  { id: 'seo-yt-title', name: 'YouTube Title Generator', desc: 'Ide judul video klikbait', category: 'seo', type: 'GenericGeneratorTool', config: 'ytTitle' },
  { id: 'seo-yt-desc', name: 'YouTube Desc Generator', desc: 'Template deskripsi video', category: 'seo', type: 'GenericGeneratorTool', config: 'ytDesc' },
  { id: 'seo-ig', name: 'Instagram Caption', desc: 'Ide caption IG menarik', category: 'seo', type: 'GenericGeneratorTool', config: 'igCaption' },
  { id: 'seo-tiktok', name: 'TikTok Caption', desc: 'Ide caption FYP', category: 'seo', type: 'GenericGeneratorTool', config: 'tiktokCaption' },
  { id: 'seo-blog', name: 'Blog Title Generator', desc: 'Ide judul artikel blog', category: 'seo', type: 'GenericGeneratorTool', config: 'blogTitle' },

  // Security
  { id: 'sec-strength', name: 'Password Strength', desc: 'Cek kekuatan kata sandi', category: 'security', type: 'SpecificTools', config: 'passStrength' },
  { id: 'sec-pass-gen', name: 'Password Generator', desc: 'Buat sandi rumit aman', category: 'security', type: 'GenericGeneratorTool', config: 'password' },
  { id: 'sec-2fa', name: '2FA QR Helper', desc: 'Generate QR untuk Autentikator', category: 'security', type: 'SpecificTools', config: '2fa' },
  { id: 'sec-hash', name: 'Hash Checker', desc: 'Bandingkan nilai hash (MD5, dll)', category: 'security', type: 'SpecificTools', config: 'hashCheck' },
  { id: 'sec-leak', name: 'Email Leak Checker', desc: 'Cek email di database bocor (HaveIBeenPwned API)', category: 'security', type: 'SpecificTools', config: 'emailLeak' },
  { id: 'sec-url', name: 'URL Safety Checker', desc: 'Periksa link phising/malware (SafeBrowsing API)', category: 'security', type: 'SpecificTools', config: 'urlSafe' },
  { id: 'sec-pin', name: 'Random PIN', desc: 'Buat PIN acak 4-6 digit', category: 'security', type: 'GenericGeneratorTool', config: 'pin' },
  { id: 'sec-number', name: 'Secure Random Number', desc: 'Angka acak kriptografik', category: 'security', type: 'GenericGeneratorTool', config: 'secureNum' },
  { id: 'sec-notes', name: 'Secure Notes Lokal', desc: 'Catatan rahasia dienkripsi di browser', category: 'security', type: 'SpecificTools', config: 'secureNotes' },

  // Random
  { id: 'rnd-number', name: 'Random Number', desc: 'Angka acak biasa', category: 'random', type: 'GenericGeneratorTool', config: 'randomNumber' },
  { id: 'rnd-name', name: 'Random Name', desc: 'Nama orang acak', category: 'random', type: 'GenericGeneratorTool', config: 'name' },
  { id: 'rnd-user', name: 'Random Username', desc: 'Username unik acak', category: 'random', type: 'GenericGeneratorTool', config: 'username' },
  { id: 'rnd-color', name: 'Random Color', desc: 'Warna acak HEX/RGB', category: 'random', type: 'GenericGeneratorTool', config: 'color' },
  { id: 'rnd-quote', name: 'Random Quote', desc: 'Kutipan motivasi/bijak acak', category: 'random', type: 'GenericGeneratorTool', config: 'quote' },
  { id: 'rnd-team', name: 'Random Team Picker', desc: 'Bagi daftar orang ke beberapa tim', category: 'random', type: 'SpecificTools', config: 'team' },
  { id: 'rnd-wheel', name: 'Random Wheel Spinner', desc: 'Roda putar keberuntungan', category: 'random', type: 'SpecificTools', config: 'wheel' },
  { id: 'rnd-dice', name: 'Dice Roller', desc: 'Lempar dadu virtual', category: 'random', type: 'SpecificTools', config: 'dice' },
  { id: 'rnd-coin', name: 'Coin Flip', desc: 'Lempar koin Head/Tail', category: 'random', type: 'SpecificTools', config: 'coin' },
  { id: 'rnd-lottery', name: 'Lottery Number', desc: 'Generator angka lotre/togel', category: 'random', type: 'GenericGeneratorTool', config: 'lottery' },
  { id: 'rnd-fake', name: 'Fake Data Generator', desc: 'Generate data dummy untuk testing (JSON)', category: 'random', type: 'GenericGeneratorTool', config: 'fakeData' },
];
